### PR TITLE
Support for custom metric

### PR DESCRIPTION
**Pull request by feribg**
This adds support for custom metrics, allows dropcol to work without OOB score and adds support for sample_weights to all scoring functions.

### CODE REVIEW

**Comment by feribg** [comment]
@parrt If the above makes sense, I think the next thing I would like to address would be allowing `metrics` to be a dict of `name` => `callable`.

**Comment by parrt** [comment]
Looks great, thanks!

**Comment by parrt** [comment]
Can you respond with a comment that you agree to release this under the MIT license of this repository?

**Comment by feribg** [comment]
I agree to release it under MIT license.

Does it push to pip automatically? Would be nice not to use my git version locally. Thanks!

**Comment by feribg** [comment]
I saw one typo that I need to reverse quickly.

**Comment by parrt** [comment]
oh. i'll wait to push

**Pull request merged**
