### PR TITLE
#5 - Full importances function always uses model.score

### PR DESCRIPTION
**Pull request by feribg**
Fix typo on callable

### CODE REVIEW

**Comment by parrt** [comment]
Extension to https://github.com/parrt/random-forest-importances/pull/6

**Comment by parrt** [comment]
Can you confirm for me locally that `python setup.py install`  gets the right stuff now after you pull from this master? if so I will push out to pypy

**Comment by feribg** [comment]
Worked well on my end

**Comment by parrt** [comment]
Pushed https://pypi.org/project/rfpimp/  thanks!

**Pull request merged**
