### PR TITLE
Added multiprocessing for oob_importances

### PR DESCRIPTION
**Pull request by RohanBhandari**
Addresses issue #19

### CODE REVIEW

**Comment by parrt** [comment]
From my initial inspection, it looks good! How widely have you tested this? ;)

**Comment by RohanBhandari** [comment]
I've mainly tested it for my use case: I fixed the random seed for the column permutations and compared the feature importances from the original code to those from the multiprocessing code and they were exactly the same.

**Comment by parrt** [comment]
I will try it out on a data set amusing myself. thank you!

**Comment by parrt** [comment]
For the record, how big was the data set you used your patch on?  I've seen the multi processing package in Python go really slow when it needs to push a lot of data around.

**Comment by parrt** [comment]
uh. this takes much longer and gets a radically different set of feature importances.  I ran it twice and the new importances don't make sense I'm afraid. Hmm... I better back this change out for now. sorry!

**Comment by RohanBhandari** [comment]
Hmm, that is strange. Did you set the random state for the column permutations (i.e. on [L405](https://github.com/RohanBhandari/random-forest-importances/blob/master/src/rfpimp.py#L405) (original) and [L420](https://github.com/RohanBhandari/random-forest-importances/blob/multiprocessing/src/rfpimp.py#L420) (modified), `np.random.permutation(foo)` -> `np.random.RandomState(42).permutation(foo)`)?

My dataset is ~10k samples, but has a couple thousand features (it's quite sparse). So in my case, at least, it dramatically improved runtime.

**Comment by RohanBhandari** [comment]
Actually, nevermind on my above comment on setting the RandomSeed. I realized that that was not the right way to set that since it was setting it locally each time instead of globally and may have been what made the results look good on my end.

I've narrowed the error to me doing a shallow copy of the X_train, so the training set was not resetting back to its original state with each loop. I've now gotten the results to match exactly with n_jobs = 1, but if I use more than 1 job, I get 99% of the features to match with slight differences in the other features. I'm still investigating this issue.

Sorry for the confusion!

**Comment by parrt** [comment]
Happy to try out a new version.  it's really too bad that Python is so terrible at threads; more precisely, it can't do threads and shared memory. :(   I also find it impossible to understand, despite 40 years of programming with lots of threads and operating systems level work.

**Comment by RohanBhandari** [comment]
Okay, so I am now able to completely reproduce the original importances with my modified code. 

The slight differences in the features I mentioned above was due to the fact that the multiprocessing doesn't necessarily execute the column permutation in order so some columns were permuted differently than if they were executed sequentially, resulting in slightly different importances. Is there a way you would like to handle this? If left as is, you may get slightly different importances (within the level of noise) depending on `n_jobs`.

**Comment by parrt** [comment]
slight differences would be expected if it is giving different permutations.  Perhaps make a new PR and I will test it on my side before merging?

**Comment by RohanBhandari** [comment]
Opened new PR #21

**Pull request merged**
